### ISSUE TITLE
Use `<a>` element with the button classes

### ISSUE THREAD

**Issue by reddo** [uwejacobs/complete-bootstrap-4-shortcodes#1]
I would like to use an `<a>` element with `href` instead of the `<button>`, but it not currently possible. Is there a way for you to add that option?

**Comment by uwejacobs** [comment]
Would you please post the complete snippet where you would like to see the <a> element instead of the <button>. I'll look into it.

**Comment by reddo** [comment]
Sorry, I forgot to add it. It would be for the `[button]` shortcode.

**Comment by uwejacobs** [comment]
I added a "tag" option to the [button] shortcode, along with parameters "link" and "target":

[button tag="a" link="https://wordpress.org/plugins/complete-bootstrap-4-shortcodes/" target="_blank"]Hyperlink[/button]

Please update to version 4.5.6 and let me know if that works for you.

**Comment by reddo** [comment]
It is working well. Thank you!
