### ISSUE TITLE
Issue on the demo page

### ISSUE THREAD

**Issue by reddo** [uwejacobs/complete-bootstrap-4-shortcodes#2]
Opening the demo page shows a few screens-full worth of the following error:

![image](https://user-images.githubusercontent.com/1180060/121487446-c334c100-c9da-11eb-8d5b-946850797ea3.png)

The same when editing this page:

![image](https://user-images.githubusercontent.com/1180060/121487831-26265800-c9db-11eb-8240-14dfd4beb93d.png)

![image](https://user-images.githubusercontent.com/1180060/121488066-64bc1280-c9db-11eb-994a-47a24e84680c.png)

**Comment by uwejacobs** [comment]
The official demo page https://ujsoftware.com/bootstrap-4-shortcodes-demo-4-5-8/ works. Did this start after an update to version 4.5.8?

**Comment by reddo** [comment]
nope, it did it with the previous version too. I have the WP_DEBUG set to true.

**Comment by uwejacobs** [comment]
Got it. Thanks for bringing this to my attention.

It will be fixed with the next version. If you don't want to wait until then, please replace the offending lines 2928-2929 with this snippet:

            if (isset($dom->documentElement->tagName)) {
                $tagname = $dom->documentElement->tagName;
            } else {
                return false;
            }

**Comment by reddo** [comment]
It can wait for the next release. Thanks!
